### ISSUE TITLE
Crash occuring when calling setEndColor without calling setTrackWidth beforehand

### ISSUE THREAD

**Issue by Sonphil** [Moosphan/Material-ProgressView#5]
Hello,

A crash occurs when setting the color without calling setTrackWidth beforehand.

<pre>
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ca.etsmtl.etsmobile, PID: 30545
                  java.lang.NullPointerException: Attempt to read from field 'float android.graphics.RectF.left' on a null object reference
                      at com.moos.library.CircleProgressView.setStartColor(CircleProgressView.java:456)
                      at ca.etsmtl.etsmobile.presentation.gradesdetails.EvaluationHeaderItem$bind$$inlined$with$lambda$1.onCircleProgressUpdate(EvaluationHeaderItem.kt:89)
                      at com.moos.library.CircleProgressView$2.onAnimationUpdate(CircleProgressView.java:615)
                      at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1522)
                      at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:987)
                      at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:654)
                      at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:617)
                      at android.animation.ValueAnimator.start(ValueAnimator.java:1046)
                      at android.animation.ValueAnimator.start(ValueAnimator.java:1065)
                      at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
                      at com.moos.library.CircleProgressView.startProgressAnimation(CircleProgressView.java:645)
</pre>

**Comment by Moosphan** [comment]
@Sonphil thanks for your feedback，it has been solved.😄

**Comment by Sonphil** [comment]
:)
